<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\ITI.ExaminationSystem.Application\ITI.ExaminationSystem.Application.csproj" />
    <ProjectReference Include="..\ITI.ExaminationSystem.Infrastructure\ITI.ExaminationSystem.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
